export const NFL_TEAMS = {
  ARI: { id: 'ARI', shortName: 'CARDINALS', fullName: 'Arizona Cardinals' },
  ATL: { id: 'ATL', shortName: 'FALCONS', fullName: 'Atlanta Falcons' },
  BAL: { id: 'BAL', shortName: 'RAVENS', fullName: 'Baltimore Ravens' },
  BUF: { id: 'BUF', shortName: 'BILLS', fullName: 'Buffalo Bills' },
  CAR: { id: 'CAR', shortName: 'PANTHERS', fullName: 'Carolina Panthers' },
  CHI: { id: 'CHI', shortName: 'BEARS', fullName: 'Chicago Bears' },
  CIN: { id: 'CIN', shortName: 'BENGALS', fullName: 'Cincinnati Bengals' },
  CLE: { id: 'CLE', shortName: 'BROWNS', fullName: 'Cleveland Browns' },
  DAL: { id: 'DAL', shortName: 'COWBOYS', fullName: 'Dallas Cowboys' },
  DEN: { id: 'DEN', shortName: 'BRONCOS', fullName: 'Denver Broncos' },
  DET: { id: 'DET', shortName: 'LIONS', fullName: 'Detroit Lions' },
  GB:  { id: 'GB',  shortName: 'PACKERS', fullName: 'Green Bay Packers' },
  HOU: { id: 'HOU', shortName: 'TEXANS', fullName: 'Houston Texans' },
  IND: { id: 'IND', shortName: 'COLTS', fullName: 'Indianapolis Colts' },
  JAX: { id: 'JAX', shortName: 'JAGUARS', fullName: 'Jacksonville Jaguars' },
  KC:  { id: 'KC',  shortName: 'CHIEFS', fullName: 'Kansas City Chiefs' },
  LV:  { id: 'LV',  shortName: 'RAIDERS', fullName: 'Las Vegas Raiders' },
  LAC: { id: 'LAC', shortName: 'CHARGERS', fullName: 'Los Angeles Chargers' },
  LAR: { id: 'LAR', shortName: 'RAMS', fullName: 'Los Angeles Rams' },
  MIA: { id: 'MIA', shortName: 'DOLPHINS', fullName: 'Miami Dolphins' },
  MIN: { id: 'MIN', shortName: 'VIKINGS', fullName: 'Minnesota Vikings' },
  NE:  { id: 'NE',  shortName: 'PATRIOTS', fullName: 'New England Patriots' },
  NO:  { id: 'NO',  shortName: 'SAINTS', fullName: 'New Orleans Saints' },
  NYG: { id: 'NYG', shortName: 'GIANTS', fullName: 'New York Giants' },
  NYJ: { id: 'NYJ', shortName: 'JETS', fullName: 'New York Jets' },
  PHI: { id: 'PHI', shortName: 'EAGLES', fullName: 'Philadelphia Eagles' },
  PIT: { id: 'PIT', shortName: 'STEELERS', fullName: 'Pittsburgh Steelers' },
  SF:  { id: 'SF',  shortName: '49ERS', fullName: 'San Francisco 49ers' },
  SEA: { id: 'SEA', shortName: 'SEAHAWKS', fullName: 'Seattle Seahawks' },
  TB:  { id: 'TB',  shortName: 'BUCCANEERS', fullName: 'Tampa Bay Buccaneers' },
  TEN: { id: 'TEN', shortName: 'TITANS', fullName: 'Tennessee Titans' },
  WAS: { id: 'WAS', shortName: 'COMMANDERS', fullName: 'Washington Commanders' }
};
